import { TableAndGridService } from "@uuv/assistant";
import { JSDOM } from "jsdom";

const innerHtml = "PHRhYmxlIGFyaWEtbGFiZWxsZWRieT0icGFnZS10aXRsZSI+CiAgICAgIDx0Ym9keT48dHI+CiAgICAgICAgPHRoIHNjb3BlPSJjb2wiPkNvbXBhbnk8L3RoPgogICAgICAgIDx0aCBzY29wZT0iY29sIj5Db250YWN0PC90aD4KICAgICAgICA8dGggc2NvcGU9ImNvbCI+Q291bnRyeTwvdGg+CiAgICAgIDwvdHI+CiAgICAgIDx0cj4KICAgICAgICA8dGQ+QWxmcmVkcyBGdXR0ZXJraXN0ZTwvdGQ+CiAgICAgICAgPHRkPk1hcmlhIEFuZGVyczwvdGQ+CiAgICAgICAgPHRkPkdlcm1hbnk8L3RkPgogICAgICA8L3RyPgogICAgICA8dHI+CiAgICAgICAgPHRkPkNlbnRybyBjb21lcmNpYWwgTW9jdGV6dW1hPC90ZD4KICAgICAgICA8dGQ+RnJhbmNpc2NvIENoYW5nPC90ZD4KICAgICAgICA8dGQ+TWV4aWNvPC90ZD4KICAgICAgPC90cj4KICAgICAgPHRyPgogICAgICAgIDx0ZD5Fcm5zdCBIYW5kZWw8L3RkPgogICAgICAgIDx0ZD5Sb2xhbmQgTWVuZGVsPC90ZD4KICAgICAgICA8dGQ+QXVzdHJpYTwvdGQ+CiAgICAgIDwvdHI+CiAgICAgIDx0cj4KICAgICAgICA8dGQ+SXNsYW5kIFRyYWRpbmc8L3RkPgogICAgICAgIDx0ZD5IZWxlbiBCZW5uZXR0PC90ZD4KICAgICAgICA8dGQ+VUs8L3RkPgogICAgICA8L3RyPgogICAgICA8dHI+CiAgICAgICAgPHRkPkxhdWdoaW5nIEJhY2NodXMgV2luZWNlbGxhcnM8L3RkPgogICAgICAgIDx0ZD5Zb3NoaSBUYW5uYW11cmk8L3RkPgogICAgICAgIDx0ZD5DYW5hZGE8L3RkPgogICAgICA8L3RyPgogICAgICA8dHI+CiAgICAgICAgPHRkPk1hZ2F6emluaSBBbGltZW50YXJpIFJpdW5pdGk8L3RkPgogICAgICAgIDx0ZD5HaW92YW5uaSBSb3ZlbGxpPC90ZD4KICAgICAgICA8dGQ+SXRhbHk8L3RkPgogICAgICA8L3RyPgogICAgPC90Ym9keT48L3RhYmxlPg==";

const tableAndGridService = new TableAndGridService();
console.log(atob(innerHtml));
console.log("\n\n");
const dom = new JSDOM(atob(innerHtml));
const element = dom.window.document.body.firstElementChild;
console.log(element.innerHTML);
const result = tableAndGridService.buildResultSentence(element as HTMLElement);
console.log(result);
