name: Npm Publish
description: Action to publish on npm registry
inputs:
  node-version:
    required: true
    description: Nodejs version
  npm-package-scope:
    required: true
    description: NPM package scope
  npm-token:
    required: true
    description: NPM Registry token
  archive-to-upload:
    required: true
    description: NPM Archive to upload
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{inputs.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version:  ${{inputs.node-version}}
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish ${{inputs.archive-to-upload}} --scope ${{inputs.npm-package-scope}} --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{inputs.npm-token}}